### ISSUE TITLE
Magic values in pipeline_layout macro  

### ISSUE THREAD

**Issue by attackgoat** [tomaka/vulkano#132]
I am trying to use this macro to produce descriptors for a compute shader that should use the storage image type, but it appears the pre-implemented image types all set 'sampled=true'.

Is there a way to specify the values I'd like to use in each struct (DescriptorImageDesc in this case)? Or would it be acceptable for me to add the missing implementation - although I see how the permutation of options could bloat the API quickly.

Missing?:
vulkano::descriptor::pipeline_layout::custom_pipeline_macro::StorageImage;

Thanks for this awesome library!

**Comment by tomaka** [comment]
This area is not finished, but yes all you need to do is implement `StorageImage` under the same model as what already exists in this module.
