### ISSUE TITLE
MissingExtension VK_KHR_xlib_surface

### ISSUE THREAD

**Issue by JustMaximumPower** [tomaka/vulkano#165]
When I try to run the examples on Ubuntu 16.04 I get the following error:

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: SurfaceCreationError(MissingExtension { name: "VK_KHR_xlib_surface" })', ../src/libcore/result.rs:746

The vulkan samples from [SaschaWillems](https://github.com/SaschaWillems/Vulkan) all run fine, so I think its not a problem of the vulkan install.

I’m running vulkano on Ubuntu 16.04 x64 with an AMD R9 380X with AMDGPU-Pro 16.30.3.

**Comment by nicokoch** [comment]
The vulkan examples of SaschaWillems use xcb, not xlib.

Sadly, xlib support is not yet implemented in the intel linux driver. You can double check this with `vulkaninfo | grep xlib`.

You can however run vulkano in a wayland context (like weston) and the examples should run fine. (I get a segfault in `libwayland_client` at some point, but that I think is a bug in the intel driver.)

**Comment by tomaka** [comment]
I'm going to close this, as this is the relevant issue: https://github.com/tomaka/winit/issues/5

Unfortunately this is a problem with the windowing library that only supports Xlib (and Wayland) and not XCB. Right now vulkano-win checks for wayland, and if it doesn't work assumes that xlib will work. Hence the problem.
