### ISSUE TITLE
Why Lifetimes?

### ISSUE THREAD

**Issue by Mixthos** [tomaka/vulkano#18]
I'm trying to build a struct that has fields for both the vulkano `Instance` and the `PhysicalDevice` I am using. In the `new` function, I first create an `Instance`, then I create a `PhysicalDevice` from it and then I create and return the instance of the struct that contains both:
```rust
// ...
pub struct Renderer<'a> {
    instance: std::sync::Arc<vk::instance::Instance>,
    physical_device: vk::instance::PhysicalDevice<'a>,
}

impl<'a> Renderer<'a> {
    pub fn new() -> Renderer<'a> {
        // ...
        let instance = vk::instance::Instance::new(Some(&app_info), &extensions, &[]).unwrap(); // TODO: deal with errors
        let physical_device = vk::instance::PhysicalDevice::enumerate(&instance).next().unwrap(); // TODO: choose correct device
        
        Renderer {
            instance: instance,
            physical_device: physical_device,
        }
    }
}
```

I get the following error:
```
renderer.rs:28:72: 28:80 error: `instance` does not live long enough
renderer.rs:28         let physical_device = vk::instance::PhysicalDevice::enumerate(&instance).next().unwrap(); // TODO: choose correct device
                                                                                      ^~~~~~~~
renderer.rs:14:34: 34:6 note: reference must be valid for the lifetime 'a as defined on the block at 14:33...
renderer.rs:14     pub fn new() -> Renderer<'a> {
renderer.rs:15         let app_info = vk::instance::ApplicationInfo {
renderer.rs:16             application_name: "vulkano-test",
renderer.rs:17             application_version: 1,
renderer.rs:18             engine_name: "vulkano-test",
renderer.rs:19             engine_version: 1,
               ...
renderer.rs:27:96: 34:6 note: ...but borrowed value is only valid for the block suffix following statement 2 at 27:95
renderer.rs:27         let instance = vk::instance::Instance::new(Some(&app_info), &extensions, &[]).unwrap(); // TODO: deal with errors
renderer.rs:28         let physical_device = vk::instance::PhysicalDevice::enumerate(&instance).next().unwrap(); // TODO: choose correct device
renderer.rs:29
renderer.rs:30         Renderer {
renderer.rs:31             instance: instance,
renderer.rs:32             physical_device: physical_device,
               ...
error: aborting due to previous error
error: Could not compile `vulkano-test`.
```

If I understand this correctly, I would have to pass a reference to the `Renderer`'s `instance` to `PhysicalDevice::enumerate` in order for Rust to understand that the `Instance` doesn't disappear after the function has finished. But then I would have to create the `Renderer` before the `PhysicalDevice`, which would mean that it can't contain the `PhysicalDevice`. (I may be misunderstanding things as I'm new to Rust.)

I don't think `PhysicalDevice` needs to use a lifetime, though, as the lifetime is just for a reference to an `Arc`. But `Arc` already makes sure that the `Instance` won't be destroyed before the `PhysicalDevice`, right? So I think that
```
pub struct PhysicalDevice<'a> {
    instance: &'a Arc<Instance>,
    device: usize,
}
```
could be replaced by
```
pub struct PhysicalDevice {
    instance: Arc<Instance>,
    device: usize,
}
```
and `enumerate` and `from_index` could just clone the `Arc` instead of saving a reference to it.
Again, I'm new to Rust and may be misunderstanding things. I'm sorry if I'm wasting your time with my confusion. ;)

**Comment by tomaka** [comment]
What you say is right. It's like trying to store a `Vec` and a reference to an element of the vec in the same struct. That's currently forbidden.

However the idea is that you should store the identifier of the physical device instead of the physical device instead. Then whenever you need a `PhysicalDevice` you call `from_index`.

For example the `Device` object does exactly this:
https://github.com/tomaka/vulkano/blob/c7532b9cce5559b0f14c9abeccf114b2018ccb95/vulkano/src/device.rs#L43-L44
https://github.com/tomaka/vulkano/blob/c7532b9cce5559b0f14c9abeccf114b2018ccb95/vulkano/src/device.rs#L164-L165
https://github.com/tomaka/vulkano/blob/c7532b9cce5559b0f14c9abeccf114b2018ccb95/vulkano/src/device.rs#L209-L213

**Comment by Mixthos** [comment]
Thanks! Could the `Arc` theoretically be replaced by references with lifetimes?

**Comment by Mixthos** [comment]
Also: Please consider renaming `index` to `id` for `PhysicalDevice` (like in `MemoryHeap` and `MemoryType`) to make the API more consistent. (I could do it if you want.)
BTW: Is it ok to open issues for tiny things like this?

**Comment by tomaka** [comment]
> BTW: Is it ok to open issues for tiny things like this?

The answer is that it depends in which part of the library the issue is. Some parts are mostly drafts, while others are more or less finished. But I don't really want to document which parts are finished yet.
