### ISSUE TITLE
std::isinf not found

### ISSUE THREAD

**Issue by LuisAyuso** [tomaka/vulkano#207]
header missing to use std::isinf
 vulkano/glsl-to-spirv/glslang/glslang/MachineIndependent/intermOut.cpp:52:15 

I included <cmath> in my working copy, but it might not be needed in all platforms

**Comment by tomaka** [comment]
I pull glslang directly from https://github.com/KhronosGroup/glslang
If they recently fixed that problem I can update the commit used by vulkano, but if they didn't then there's nothing I can do.

**Comment by LuisAyuso** [comment]
my bad, I will report there then.
