### ISSUE TITLE
can't find crate for `vulkano_shaders`

### ISSUE THREAD

**Issue by humb1t** [tomaka/vulkano#233]
Hello, I'm tried to use vulkano-shaders in my tests. I created build.rs and added:
`extern crate vulkano_shaders;` to it.
But there is an error in compile time: 
`tests/build.rs:1:1: 1:30 error: can't find crate for `vulkano_shaders` [E0463]
tests/build.rs:1 extern crate vulkano_shaders;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error`

If I will try to use vulkano-shaders, compile also failed.

**Comment by tomaka** [comment]
You probably forgot to put the dependency under `[build-dependencies]`, like here: https://github.com/tomaka/vulkano/blob/master/examples/Cargo.toml#L14-L16

**Comment by humb1t** [comment]
Dear tomaka, no, I did it. I checked crate on crates.io too, I can provide detailed information of project structure and configuration when I will get to home.

**Comment by humb1t** [comment]
[anduin.zip](https://github.com/tomaka/vulkano/files/437307/anduin.zip)

**Comment by tomaka** [comment]
If you put `build.rs` in your `tests` directory, Cargo will think that it's a test.
Anyway, I'm closing since this is not an issue with vulkano.

**Comment by humb1t** [comment]
I`m really sorry for waste of your time. That was a cause. Thank you.
