### ISSUE TITLE
Recommended video card?

### ISSUE THREAD

**Issue by MarkSwanson** [tomaka/vulkano#241]
What video card do you (tomaka) use?

I ask because I'm going to buy a new video card to play with Vulkan and would like to use  something that is close in hardware and the same driver number as you if possible. So if I have weird problems you should be able to reproduce...

I'm thinking of sticking an AMD 460 into my lInux router at home. I can always connect to it, and I'm only interested in Vulkan compute.

Thanks!

**Comment by tomaka** [comment]
All the drivers that are supposed to be mature do indeed work very well. The problem is that on linux as far as I know the only mature driver is nvidia's.

**Comment by tomaka** [comment]
To answer your question, I'm using Nvidia + Windows. I also tried Amd + windows and Nvidia + android and they work well. I also tried the experimental Intel linux driver but it's really too experimental for now. I haven't tried anything else.

**Comment by MarkSwanson** [comment]
Thanks!
