### ISSUE TITLE
Building issue (maybe due to use of Cargo workspace)

### ISSUE THREAD

**Issue by killkrt** [tomaka/vulkano#251]
Hi,

I've noticed that the building process of this library is different from classic Rust libs or maybe (for sure ;-)) I'm doing something wrong.

When I run in the main folder:
`cargo build`

I get this error (with stable Rust 1.11.0):
```
error: failed to parse manifest at /home/killkrt/Development/vulkano/Cargo.toml

Caused by:
  no package or project section found.
```

And this error with nightly (1.13.0-923bac459):
```
error: manifest path `/home/killkrt/Development/vulkano/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

Anyway I was able to build each crate by myself going in each folder and launching `cargo build`.

As I understood cargo workspace are a new feature, but they should work with nightly release.
Anyway I think it should be mentioned in the `README.md `that you need a nightly version in order to build this lib and how.

Thank you.

**Comment by tomaka** [comment]
Yes the crate is using workspaces.
The fact that you have to go in each directory is normal. The purpose of using a workspace is that all the crates share the same `target` directory.

**Comment by killkrt** [comment]
Thank you!
