### ISSUE TITLE
Example for UniformBuffer update

### ISSUE THREAD

**Issue by Batanick** [tomaka/vulkano#254]
Suppose we want to add camera rotation to our fancy teapot example. In the example we have 2 _command buffers_ with shared _uniform buffer_ and  _pipeline_layout::set0::Set_ attached to them. How can we perform an update on each frame? 

1. Do we need to create 3 uniform buffers for this? 
1. Do we need to update _uniform buffer_ directly or do some magic with _pipeline_layout::set0::Set_ ?

**Comment by tomaka** [comment]
If the uniform buffer contained a large amount of data, you would need to create 3 uniform buffers and create a new descriptor set before each rendering.

There is a technique that vulkano does not yet support: you can create just one buffer that you split in three parts, and when you bind the descriptor sets you can specify an offset in the buffer for the start of the data. This technique has the advantage that you're only using one buffer and that the descriptor set stays the same.

However for small amounts of data (like here), you can just either use an `update_buffer` command in the command buffer, or use push constants (which are like uniforms, but limited to 128 bytes of data).

**Comment by Batanick** [comment]
Thanks for the answer, took some time to figure out.
