### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by nicokoch** [tomaka/vulkano#3]
Ok, so I ran into several problems when building on linux, one of which is easily solved:

1. KhronosGroup/glslang does not compile on linux with your included version. This issue was fixed by KhronosGroup/glslang#172 , so you should update that.
2. There is an error when building winit. I'm using multirust so I'm not really sure if this happens with a normal rust install. This is the output:
```
Compiling winit v0.4.8 (https://github.com/tomaka/winit#b4d4fee8)
/home/kokxx/.multirust/toolchains/nightly/cargo/git/checkouts/winit-a80c9921f4b7860e/master/src/api/x11/ffi.rs:14:5: 14:60 error: environment variable `OUT_DIR` not defined
/home/kokxx/.multirust/toolchains/nightly/cargo/git/checkouts/winit-a80c9921f4b7860e/master/src/api/x11/ffi.rs:14     include!(concat!(env!("OUT_DIR"), "/glx_bindings.rs"));
                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kokxx/.multirust/toolchains/nightly/cargo/git/checkouts/winit-a80c9921f4b7860e/master/src/api/x11/ffi.rs:14:5: 14:60 error: couldn't read "/home/kokxx/.multirust/toolchains/nightly/cargo/git/checkouts/winit-a80c9921f4b7860e/master/src/api/x11/0/glx_bindings.rs": No such file or directory (os error 2)
/home/kokxx/.multirust/toolchains/nightly/cargo/git/checkouts/winit-a80c9921f4b7860e/master/src/api/x11/ffi.rs:14     include!(concat!(env!("OUT_DIR"), "/glx_bindings.rs"));
                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not compile `winit`.

To learn more, run the command again with --verbose.
```

**Comment by tomaka** [comment]
1. Will do!
2. I haven't updated `winit` to compile on Linux yet.

**Comment by nicokoch** [comment]
Ah, thanks! I could probably hack around the `VK_KHR_surface_win32` thing. About winit I know nothing

**Comment by tomaka** [comment]
It should be possible to use it on Linux now.

You just have to adjust these lines:
- https://github.com/tomaka/vulkano/blob/2a6252efbe32ca4e55a9822ece179da69f705075/vulkano/examples/teapot.rs#L4-L5
- https://github.com/tomaka/vulkano/blob/2a6252efbe32ca4e55a9822ece179da69f705075/vulkano/examples/teapot.rs#L30-L31
- https://github.com/tomaka/vulkano/blob/2a6252efbe32ca4e55a9822ece179da69f705075/vulkano/src/instance.rs#L107

**Comment by nicokoch** [comment]
Thanks for the quick support!
I fixed most of the problems, but I'm not really sure how to create the surface.
I can't do `Surface::from_hwnd`, because that's windows only. Can I somehow use `from_display_mode`, or should I implement a linux version manually?

**Comment by tomaka** [comment]
Oh I forgot to push my commit. It should be good now.

**Comment by nicokoch** [comment]
Works now, thanks a lot!

**Comment by tomaka** [comment]
The examples should now work out-of-the-box on Linux.
