### ISSUE TITLE
capability "shader_clip_distance" not enabled

### ISSUE THREAD

**Issue by Zolmeister** [tomaka/vulkano#306]
The Triangle example panics during shader loading

```
Using device: Intel(R) Iris Graphics 540 (Skylake GT3e) (type: IntegratedGpu)
thread 'main' panicked at 'capability "shader_cull_distance" not enabled'
```

Generated by: https://github.com/tomaka/vulkano/blob/master/vulkano-shaders/src/lib.rs#L136

Commenting out the panic leads to:
```
spirv/spirv_to_nir.c:2341 WARNING: Unsupported SPIR-V capability: ClipDistance
```
(which seemingly gets the example to work)

I'm just getting started with Vulkan, so I'm unsure if this is a driver issue (intel) or an issue with GLSL -> SPIR-V. I couldn't figure out how to load a SPIR-V shader directly, but would like to if it's a potential solution.

**Comment by tomaka** [comment]
Are you using the version of vulkano from crates.io?

Basically this problem comes from the GLSL->SPIR-V compiler, which marks this feature as required even though the shader doesn't use it.
In theory it is fixed on master.

**Comment by Zolmeister** [comment]
@tomaka using `master` solved it, thanks
