### ISSUE TITLE
Make DeviceExtensions and InstanceExtensions extensible

### ISSUE THREAD

**Issue by tomaka** [tomaka/vulkano#315]
Right now if you initialize the extensions with `DeviceExtensions { foo: true, bar: true }` and a new members is added, the code will break.

Unfortunately, Rust's rules doesn't allow the trick where you add a private field to a struct (see https://github.com/rust-lang/rfcs/blob/master/text/0736-privacy-respecting-fru.md).

**Comment by tomaka** [comment]
Marking as "easy" and "workable", but basically I have no idea how to fix it. If someone has an idea, it should be easy to implement.

**Comment by Mixthos** [comment]
Doesn't the alternative trick mentioned in the RFC work in this case?

````rust
pub struct Bar { pub a: u8, pub b: String, pub _hidden: BarHidden }
pub struct BarHidden { _cannot_construct: () }
```

**Comment by tomaka** [comment]
Oh I didn't even read the RFC to the end!

**Comment by Mixthos** [comment]
I'll implement it then. ;)
Should the PR go to `master` or `incoming`?

**Comment by tomaka** [comment]
`incoming` doesn't touch this area so you can put that in `master`
