### ISSUE TITLE
Arbitrary Duration in Submission::drop?

### ISSUE THREAD

**Issue by Binero** [tomaka/vulkano#346]
What is the reason for this weird Duration at Submission::drop? Why is it equal to u64::MAX divided by a billion? 

https://github.com/tomaka/vulkano/blob/master/vulkano/src/command_buffer/inner.rs#L2114

**Comment by tomaka** [comment]
We creation a Duration of u64::MAX nanoseconds.

**Comment by Binero** [comment]
Which I presume is the maximum supported by Vulkan?

**Comment by tomaka** [comment]
Yes. Any higher Duration will panic I think.

**Comment by tomaka** [comment]
Closing as code has been reworked and all timeouts are now optional.
