### ISSUE TITLE
Pass PhysicalDevice by value

### ISSUE THREAD

**Issue by Binero** [tomaka/vulkano#349]
It seems like there is some instances where the library doesn't pass `PhysicalDevice` by value, as it should, but by reference.

I found one such case: https://github.com/tomaka/vulkano/blob/master/vulkano/src/device.rs#L162

According to the documentation, a `PhysicalDevice` should be passed by value, and not by reference: https://docs.rs/vulkano/0.3.1/vulkano/instance/struct.PhysicalDevice.html

Changing this would of course be breaking.

**Comment by rukai** [comment]
This can be closed now.
