### ISSUE TITLE
Segmentation fault on window creation

### ISSUE THREAD

**Issue by Yamakaky** [tomaka/vulkano#365]
I'm doing https://github.com/Yamakaky/cendre. While running the example in the readme, I get a segfault in the [call to `CreateXlibSurfaceKHR`](https://github.com/tomaka/vulkano/blob/master/vulkano/src/swapchain/surface.rs#L205). The reason is that the `dpy` field set just above is `NULL`.

**Comment by tomaka** [comment]
I don't really understand what you're doing. The `dpy` field is simply the value passed as parameter, and calling `from_xlib` with a null value is invalid.

**Comment by Yamakaky** [comment]
I'm implementing `libvulkan.so` as a software renderer. According to the Vulkan doc, vulcano should not pass a NULL dpy field. I didn't modify the source of vulkano or the example so it should not happen. Or maybe I didn't implement my code right ?

**Comment by tomaka** [comment]
It's probably a bug in winit: https://github.com/tomaka/vulkano/blob/948ecc0fb780e87253cf2bd48f44188bda0c0142/vulkano-win/src/lib.rs#L135

**Comment by Yamakaky** [comment]
Same thing with XCB.

**Comment by tomaka** [comment]
The triangle example works on my machine and passes a valid X11 connection.

**Comment by tomaka** [comment]
And the problem is that you're defining `flags` as `()` while in reality it's a `u32`: https://github.com/Yamakaky/cendre/blob/master/src/surface/xlib.rs#L15

**Comment by Yamakaky** [comment]
Why did I do that...
