### ISSUE TITLE
No `fifo` present mode

### ISSUE THREAD

**Issue by torkleyy** [tomaka/vulkano#389]
I'm using an `Intel(R) Kabylake GT2` (graphics chip of `Intel® Core™ i5-7200U`) and the following lines

```rust
let caps = window.surface()
    .get_capabilities(&physical)
    .expect("Failed to get capabilities");
println!("Present modes: {:#?}", caps.present_modes);
```

print

```
Present modes: SupportedPresentModes {
    immediate: false,
    mailbox: true,
    fifo: false,
    relaxed: false
}
```

However, [the docs](https://docs.rs/vulkano/0.3.2/vulkano/swapchain/struct.Capabilities.html) state that `fifo` is guaranteed to be true. I'm using `winit` and `vulkano-win` for window creation (just like the triangle example).

**Comment by tomaka** [comment]
That's probably a driver bug.
See this: https://github.com/tomaka/vulkano/blob/master/vulkano/src/swapchain/surface.rs#L436-L438
