### ISSUE TITLE
Creating command buffers per frame leading to a memory leak

### ISSUE THREAD

**Issue by dwerner** [tomaka/vulkano#409]
Using Vulkano 0.3.2

I have an application that constructs a scene graph and pulls together all the geometry and per-object transformations at render time, where I am using caching `CpuAccessibleBuffer` structs in a lookup. I am using `PrimaryCommandBufferBuilder` and performing `draw_inline()` with some push constants.

I try to compile all my commands into a single buffer per scene graph and include them in a single submission. I see this showing up in any size of scene, and not particularly faster with larger scenes, so I'm thinking it's not geometry data itself that's getting duped and held on to.

Regardless of the number of buffers, and my speculation, if I generate my command buffers each frame, it looks like I'm getting a memory leak. There is a limited amount of time before an OOM is imminent (GPU stops drawing), and I'm roughly certain that I'm not holding on to and duplicating data in my application. It should be noted that if I clear my lookup Vec of it's cached `CpuAccessibleBuffer`s, I see memory use drop back to the ambient level, even if it has grown significantly first.

Here, I've highlighted the memory use pattern (scene is staying the same in structure, with dynamic transformations, etc), and circled is where I free my cache of `Arc<CpuAccessibleBuffer>` - memory use drops to normal, but then ramps up again as I am keeping those around again.

![image](https://cloud.githubusercontent.com/assets/1497784/24596358/8f9dd40a-17f3-11e7-925e-15fbfe97a710.png)

Heap profiling with visual studio in windows, and judging by the graph of memory use, it looks like vulkano is holding on to a Vec, which roughly doubles in size. This fits what Vec is doing as items are added and it needs to meet the need and increases it's capacity. The method implicated is:

`vulkano::command_buffer::inner::submit<alloc::arc::Arc<vulkano::command_buffer::pool::standard::StandardCommandPool>>`

It's my understanding that I should be able to create command buffers each frame with Vulkan, admittedly I'm new to the domain. This could well be that I'm new to Vulkan, but I'm also happy to write up test cases, share code, if need be. Also, I found #126, so perhaps this is already addressed in `incoming`?

VS Heap Profiler, snapshot showing a single large allocation
![image](https://cloud.githubusercontent.com/assets/1497784/24596206/60dfe848-17f2-11e7-96f0-8f35436bde18.png)

**Comment by dwerner** [comment]
Here you can see the idle behavior while hanging on to those `CpuAccessibleBuffer`s

![image](https://cloud.githubusercontent.com/assets/1497784/24642488/79562de0-18bc-11e7-974c-89841fad05de.png)

**Comment by tomaka** [comment]
As you said, chances are that this has already been addressed.

**Comment by dwerner** [comment]
Would you recommend directly pointing at `incoming` instead?

**Comment by tomaka** [comment]
`incoming` is harder to use because it didn't get as many usability tweaks and lacks documentation a bit. It also probably doesn't work correctly on AMD drivers because it doesn't handle image layout transitions correctly yet.

**Comment by dwerner** [comment]
I'm ok with reading the code a bit, no sense in staying on an old version if it's not going to be maintained anyhow. Thanks for the feedback.

**Comment by tomaka** [comment]
I'm going to try merge incoming "soon"-ish anyway.

**Comment by dwerner** [comment]
I'll assume there are some API changes, so this gives me a chance to get to know what they are before incoming lands.
