### ISSUE TITLE
Extensions API

### ISSUE THREAD

**Issue by Mixthos** [tomaka/vulkano#42]
There are already some new layers and extensions, like the steam overlay, that aren't covered in the Vulkan spec. They should be useable with Vulkano, but they shouldn't all be included in the Vulkano crate.

I propose an extensions API that makes it possible to implement 3rd-party extension. Standard extensions like the WSI extensions would also use that API, but would still be implemented in the Vulkano crate.

I will create a pull request with an example of how that might look. If you're okay with it, I'll continue to implement it and create the missing comments.

**Comment by tomaka** [comment]
Layers and extensions are two different things.

Layers don't need support in vulkano at all (except to enumerate them) as they are supposed to be transparent. You can even inject them with environment variables if you want.

On the other hand, extensions do need full support from vulkano. For example how are you going to handle an extension that adds a new type of memory? Or an extension that adds new flags when creating an image? There's no other choice but to integrate them directly in the memory-handling code or the image-handling code.

**Comment by Mixthos** [comment]
I may have misunderstood this line in the spec:

> However, layers can expose their own extensions, which in turn are allowed to expose new commands and tokens.

So when I saw the layer `VK_LAYER_VALVE_steam_overlay`, I thought it would enable an extension for the steam overlay. It doesn't. It probably intercepts `vkQueuePresentKHR` instead.

These are the layers and extensions available on my system:

```
--- Instance ---
Core extensions:
  VK_KHR_win32_surface
  VK_KHR_surface
  VK_EXT_debug_report

Layers and their extensions:
  VK_LAYER_LUNARG_parameter_validation
    VK_EXT_debug_report
  VK_LAYER_LUNARG_object_tracker
    VK_EXT_debug_report
  VK_LAYER_VALVE_steam_overlay
  VK_LAYER_LUNARG_standard_validation
  VK_LAYER_LUNARG_screenshot
  VK_LAYER_LUNARG_image
    VK_EXT_debug_report
  VK_LAYER_LUNARG_swapchain
    VK_EXT_debug_report
  VK_LAYER_LUNARG_device_limits
    VK_EXT_debug_report
  VK_LAYER_GOOGLE_threading
    VK_EXT_debug_report
  VK_LAYER_LUNARG_api_dump
  VK_LAYER_RENDERDOC_Capture
  VK_LAYER_LUNARG_vktrace
  VK_LAYER_GOOGLE_unique_objects
  VK_LAYER_LUNARG_core_validation
    VK_EXT_debug_report

--- Device ---
Core Extensions:
  VK_KHR_swapchain
  VK_NV_glsl_shader
  VK_KHR_sampler_mirror_clamp_to_edge

Layers and their extensions:
  VK_LAYER_LUNARG_api_dump
  VK_LAYER_LUNARG_core_validation
  VK_LAYER_LUNARG_device_limits
  VK_LAYER_LUNARG_image
  VK_LAYER_LUNARG_object_tracker
  VK_LAYER_LUNARG_parameter_validation
  VK_LAYER_LUNARG_screenshot
  VK_LAYER_LUNARG_swapchain
  VK_LAYER_GOOGLE_threading
  VK_LAYER_GOOGLE_unique_objects
  VK_LAYER_LUNARG_vktrace
  VK_LAYER_RENDERDOC_Capture
    VK_LUNARG_DEBUG_MARKER
  VK_LAYER_VALVE_steam_overlay
  VK_LAYER_LUNARG_standard_validation
```

The only extensions exposed by layers are `VK_EXT_debug_report` and `VK_LUNARG_DEBUG_MARKER`. (And `VK_EXT_debug_report` is available without any layer anyway.) I guess extensions enabled by layers are only meant for debugging?

> On the other hand, extensions do need full support from vulkano. For example how are you going to handle an extension that adds a new type of memory? Or an extension that adds new flags when creating an image? There's no other choice but to integrate them directly in the memory-handling code or the image-handling code.

It _might_ be possible to give extensions access to these things by having the extensions specify callbacks and calling them in the appropriate places. (That could also be useful for custom extensions that don't rely on Vulkan extensions.) But that would mean having to add support for extensions all over the place and is probably not that useful anyway.

**Comment by tomaka** [comment]
> However, layers can expose their own extensions, which in turn are allowed to expose new commands and tokens.

If a layer exposes an extension, that means it needs some sort of support by the program that wants to use it. If an extension doesn't need any support from the program, then the layer itself could automatically enable the extension's behavior.

In any case I don't see any situation where a superficial support for vulkano for an extension would be helpful.

Anyway, my plan for extensions is to add support for things that are more-or-less-core-but-not-really-core, like WSI or debug callback. If AMD or Nvidia release an extension then Vulkano wouldn't support it, unless it's becoming popular and supported on devices from other vendors as well.

**Comment by Mixthos** [comment]
Seems like I misunderstood the extension system. Thanks for clearing that up. ;)
