### ISSUE TITLE
CommandBufferBuilder::update_buffer is unusable

### ISSUE THREAD

**Issue by Ralith** [tomaka/vulkano#493]
[`update_buffer`](https://docs.rs/vulkano/0.4.0/vulkano/command_buffer/trait.CommandBufferBuilder.html#method.update_buffer) requires `AddCommand<CmdUpdateBuffer<B, D>>` requires `CmdUpdateBuffer<B, D>: Send + Sync + 'static`, but [`CmdUpdateBuffer`](https://docs.rs/vulkano/0.4.0/vulkano/command_buffer/commands_raw/struct.CmdUpdateBuffer.html) is never `Send` or `Sync` because [it contains a raw pointer](https://docs.rs/vulkano/0.4.0/src/vulkano/command_buffer/commands_raw/update_buffer.rs.html#44) and has no explicit implementation of those traits. I'm not sure what invariants are supposed to apply here or I'd make a PR myself.

This is the one blocking issue that I ran into updating my code from 0.3.2.

**Comment by tomaka** [comment]
This raw pointer is an artefact from before a rework and should be removed.
