### ISSUE TITLE
dst/dest inconsistency

### ISSUE THREAD

**Issue by tomaka** [tomaka/vulkano#51]
Some parts of the library (eg. struct members or function names) use `dst` and some others use `dest` as a shorthand for "destination".

I suggest that they should just all be renamed to "destination", and "src" renamed to "source".

**Comment by tyoc213** [comment]
I would take this, but I have seen more like dstSome and things like that, not only in rs files, but also in cpp, so?

**Comment by tomaka** [comment]
The .cpp files and vk-sys shouldn't be touched. Their content are not chosen by us.

**Comment by tyoc213** [comment]
What about constants and enums??

```
pub enum BlendFactor {
...
    SrcColor = vk::BLEND_FACTOR_SRC_COLOR,
}
```

**Comment by tomaka** [comment]
That's a good question. People may except that the vulkano's constants are the same as Vulkan constants. It might be confusing if they have a different name.

**Comment by tyoc213** [comment]
so this one

```
    PresentSrc = vk::IMAGE_LAYOUT_PRESENT_SRC_KHR,

```

should be


```
    PresentSrcKhr = vk::IMAGE_LAYOUT_PRESENT_SRC_KHR,
```
???
