### ISSUE TITLE
Unsized arrays in shaders

### ISSUE THREAD

**Issue by fst3a** [tomaka/vulkano#526]
Hello,

I'm not sure if this is the right place to ask so excuse me if it is so, I've been writing a compute shader with vulkano and ran into a problem:

Say we have a compute shader with unsized arrays

```
#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout(set = 0, binding = 0, std430) readonly buffer A {
    float a[];
};
layout(set = 0, binding = 1, std430) writeonly buffer B {
    float b[];
};

void main() {
    uint x = gl_GlobalInvocationID.x;
    b[x] = a[x] * a[x];
}
```

When trying to create a buffer of type A or B in Rust with `::from_data`, e.g.
```
let a = CpuAccessibleBuffer::from_data(
    device.clone(),
    BufferUsage::all(),
    Some(queue.family()),
    cs::ty::A { a: [0.0; 512] }
).unwrap();
```
it will fail because A is unsized.

If I try to create an array of floats directly, as
```
let a = CpuAccessibleBuffer::from_data(
    device.clone(),
    BufferUsage::all(),
    Some(queue.family()),
    [0.0_f32; 512]
).unwrap();
```
then it will fail at creation of descriptor set with `simple_descriptor_set!`.

As of latest version of vulkano, are there ways to work with unsized arrays in the shaders?

**Comment by tomaka** [comment]
The second method should work, and the error with the descriptor set is probably unrelated.

**Comment by fst3a** [comment]
Aha, interesting.  Apparently the reason simple_descriptor_set! was failing was because the buffer itself was anonymous and it is not possible to work with the buffers' fields directly from the set.  Naming the buffers and working with the buffers instead of their fields fixes the problem.
```
 layout(binding = 0) buffer A {
     float a[];
-};
+} u;
```
