### ISSUE TITLE
Modify `swapchain.rs` to use undeprecated functions

### ISSUE THREAD

**Issue by GuildMasterInfinite** [tomaka/vulkano#530]
The [`swapchain.rs`](https://github.com/tomaka/vulkano/blob/master/vulkano/src/swapchain/swapchain.rs) file uses the [`get_capabilities()`](https://docs.rs/vulkano/0.4.1/vulkano/swapchain/struct.Surface.html#method.get_capabilities) function, which is deprecated.

Instead, the new [`capabilities()`](https://docs.rs/vulkano/0.4.1/vulkano/swapchain/struct.Surface.html#method.capabilities) function should be used.

However, because `get_capabilities` always `unwrap`s and returns `Ok()` , and `capabilities` returns `CapabiltiesError`, there might be some modification needed to the `Swapchain::new_inner` function.

<hr/>

One possible solution that doesn't change the API or contain any sort of externally visible change is to use the new function and `panic!` on error:

```rust
let capabilities = match surface.capabilities(device.physical_device()) {
            Ok(caps) => caps,
            Err(err) => match err {
                CapabilitiesError::OomError(oom_err) => return Err(oom_err),
                CapabilitiesError::SurfaceLost => panic!("Surface lost while creating swapchain")
            }
        };
```

**Comment by tomaka** [comment]
Needs to modify the error returned when creating a swapchain.
