### ISSUE TITLE
How to bind compute shader buffer descriptor?

### ISSUE THREAD

**Issue by daiheitan** [tomaka/vulkano#532]
Sorry if this is a dumb question. I could not find a way to properly set up a CpuAccessibleBuffer for compute shader and get the result later in host program. like

```
layout(set= 0, binding=1, std430) writeonly buffer OutputBuffer {
    uvec4 data[];
};
```

All examples I could find are using removed APIs of old vulkano.

Also as I am using compute shader, the window system/ event poll are not handy. Is it true that when a `GpuFuture` is dropped, the result is returned from gpu to cpu? The documentation on this is also not clear.

**Comment by tomaka** [comment]
I added a basic compute shader example which may be useful: https://github.com/tomaka/vulkano/blob/master/examples/src/bin/basic-compute-shader.rs

**Comment by daiheitan** [comment]
Wow, thanks for the quick reply and detailed explanation in the example!
