### ISSUE TITLE
Running example leads to 'main' thread panic

### ISSUE THREAD

**Issue by VoidNoire** [tomaka/vulkano#569]
Running vulkaninfo returns:
`VULKAN INFO
===========

Vulkan API Version: 1.0.51

INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_standard_validation.json, version "1.1.1"
INFO: [loader] Code 0 : Encountered meta-layer VK_LAYER_LUNARG_standard_validation
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /home/user1x/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json, version "1.0.0"
INFO: [loader] Code 0 : Found manifest file /home/user1x/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json, version "1.0.0"
INFO: [loader] Code 0 : Meta-layer VK_LAYER_LUNARG_standard_validation all 5 component layers appear to be valid.
INFO: [loader] Code 0 : Found ICD manifest file /usr/share/vulkan/icd.d/radeon_icd.x86_64.json, version "1.0.0"

Instance Extensions:
====================
Instance Extensions     count = 6
        VK_KHR_surface                      : extension revision 25
        VK_KHR_xcb_surface                  : extension revision  6
        VK_KHR_xlib_surface                 : extension revision  6
        VK_KHR_wayland_surface              : extension revision  5
        VK_KHR_get_physical_device_properties2: extension revision  1
        VK_EXT_debug_report                 : extension revision  8
WARNING: radv is not a conformant vulkan implementation, testing use only.

Layers: count = 8
=======
VK_LAYER_GOOGLE_unique_objects (Google Validation Layer) Vulkan version 1.0.51, layer version 1
        Layer Extensions        count = 0
        Devices         count = 1
                GPU id       : 0 (AMD RADV MULLINS)
                Layer-Device Extensions count = 0

VK_LAYER_GOOGLE_threading (Google Validation Layer) Vulkan version 1.0.51, layer version 1
        Layer Extensions        count = 1`

Running RUST_BACKTRACE=1 cargo run -p examples --bin triangle returns:
`    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target/debug/triangle`
WARNING: radv is not a conformant vulkan implementation, testing use only.
Using device: AMD RADV MULLINS (type: IntegratedGpu)
thread 'main' panicked at 'assertion failed: self.secondary_cb || self.subpasses_remaining.is_none()', vulkano/src/command_buffer/auto.rs:105
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: <vulkano::command_buffer::auto::AutoCommandBufferBuilder<P>>::build
             at ./<panic macros>:3
   7: triangle::main
             at examples/src/bin/triangle.rs:346
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  10: main
  11: __libc_start_main
  12: _start
thread 'main' panicked at 'explicit panic', vulkano/src/swapchain/swapchain.rs:804
stack backtrace:
   0:     0x558563cc38f3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hd5d75828cbd0c276
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x558563cc0434 - std::sys_common::backtrace::_print::h724a633dd8a7d847
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x558563cc5324 - std::panicking::default_hook::{{closure}}::hba3c453d23e47e38
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x558563cc4e13 - std::panicking::default_hook::h90ed4d9f5855fbee
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x558563cc57aa - std::panicking::rust_panic_with_hook::hfa84a713ba589573
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x558563b0a079 - std::panicking::begin_panic::hcceab8e14e7c7526
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x558563b8c881 - <vulkano::swapchain::swapchain::SwapchainAcquireFuture as core::ops::drop::Drop>::drop::hfecaf60ad658ed5e
                               at vulkano/src/swapchain/swapchain.rs:804
   7:     0x558563a27a34 - core::ptr::drop_in_place::h01c0eb216b90156a
                               at /checkout/src/libcore/ptr.rs:60
   8:     0x558563adaac0 - triangle::main::hf80c6a23c63324fa
                               at examples/src/bin/triangle.rs:405
   9:     0x558563ccc72c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  10:     0x558563cc5f44 - std::rt::lang_start::h07ddbcdd00d185d4
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  11:     0x558563adf3e2 - main
  12:     0x7f7b9c3a6439 - __libc_start_main
  13:     0x5585639a8149 - _start
  14:                0x0 - <unknown>
thread panicked while panicking. aborting.`

**Comment by tomaka** [comment]
Thanks for the report. I just fixed it moments ago in #568.
