### ISSUE TITLE
Do not create a new semaphore/event/fence every time

### ISSUE THREAD

**Issue by tomaka** [tomaka/vulkano#589]
According to AMD's "Most common Vulkan mistakes" (which I found on twitter I think, but I can't find it anymore) you should avoid doing this at all cost.

**Comment by tomaka** [comment]
Marking as "hard" because it needs some thinking about which API to provide.

**Comment by mollyporph** [comment]
Dominik's talk sadly did not get recorded, but I found the slides here for reference: http://32ipi028l5q82yhj72224m8j.wpengine.netdna-cdn.com/wp-content/uploads/2016/05/Most-common-mistakes-in-Vulkan-apps.pdf

**Comment by tomaka** [comment]
Yeah those were the slides I was thinking of!

**Comment by tomaka** [comment]
The obvious solution would be to create some sort of pool for fences and semaphores in the `Device` struct. When a semaphore or a fence is dropped, it is instead added back to the pool.
However since the `Fence` and `Semaphore` structs contain an `Arc<Device>`, we would have a cyclic reference.

We could simply store raw fences and semaphores in the `Device`, and modify `Fence` and `Semaphore` to use the pool. In other words `Fence::new` would pick a raw `vkFence` from the pool instead of creating an actual fence (unless the pool is empty, in which case we do need to create one). Its destructor would put back the `vkFence` in the pool.

However I think this should be made explicit, otherwise this may look a bit too magic. After all when I call `Fence::new`, I expect to see `vkCreateFence` in the list of API calls.
Therefore I think we should rename `Fence`'s and `Semaphore`'s methods. `Fence::alloc` would create a fresh new fence all the time, and `Fence::from_pool` would try to pick a fence from the device's pool (or call `alloc` if the pool is empty). `Fence::new` would be deprecated. Same for `Semaphore`.

**Comment by nicokoch** [comment]
Hey, here's some API-related questions that emerged after reading your latest comment:
- You talk about Fences and Semaphores, but not Events. Do the concepts also apply to Events?
- Would a Fence created with `Fence::alloc` be put in the pool on `drop`, or would it be freed?
- Should `Fence::signaled()` be deprecated in favor of `Fence::alloc_signaled()`?
- Is something like `Fence::from_pool_signaled()` possible, and should it be created?

**Comment by nicokoch** [comment]
I'll try to wire something up, if that's fine for you

**Comment by nicokoch** [comment]
@tomaka implemented in https://github.com/nicokoch/vulkano/commit/99729ad9a7beed336b1399765312a0bcf9a10f86 (for now only `Fence`)

If the approach works for you, I will follow up with Event and Semaphore.

**Comment by tomaka** [comment]
@nicokoch I made some comments on your commit, but it's good overall!

**Comment by nicokoch** [comment]
@tomaka this can be closed
