### ISSUE TITLE
Runtime error during the triangle example

### ISSUE THREAD

**Issue by Nijaitchy** [tomaka/vulkano#612]
When running the source code of triangle.rs the program ends up panicking during this function call.
 ```
let extensions = vulkano_win::required_extensions();
```
which leads to line 318 of vulkano-0.5.0/src/instance.rs/extensions.rs where the actually error happens:

thread 'main' panicked at 'OutOfHostMemory', ...\.cargo\registry\src\github.com-[...]\vulcano-0.5.0\src\instance\extensions.rs:318

```
instance_extensions! {
    InstanceExtensions,
    RawInstanceExtensions,
    khr_surface => b"VK_KHR_surface",
    khr_display => b"VK_KHR_display",
    khr_xlib_surface => b"VK_KHR_xlib_surface",
    khr_xcb_surface => b"VK_KHR_xcb_surface",
    khr_wayland_surface => b"VK_KHR_wayland_surface",
    khr_mir_surface => b"VK_KHR_mir_surface",
    khr_android_surface => b"VK_KHR_android_surface",
    khr_win32_surface => b"VK_KHR_win32_surface",
    ext_debug_report => b"VK_EXT_debug_report",
    mvk_ios_surface => b"VK_MVK_ios_surface",
    mvk_macos_surface => b"VK_MVK_macos_surface",
    mvk_moltenvk => b"VK_MVK_moltenvk",     // TODO: confirm that it's an instance extension
    nn_vi_surface => b"VK_NN_vi_surface",
    ext_swapchain_colorspace => b"VK_EXT_swapchain_colorspace",
    khr_get_physical_device_properties2 => b"VK_KHR_get_physical_device_properties2",
}
```

After searching for the problem myself I found some sources suggesting that my graphic card/driver does not support vulkan, but according to the official AMD website this shouldn't be the case
(AMD Radeon R7 240 in case this is up being relevant)

**Comment by tomaka** [comment]
I guess that `vkEnumerateInstanceExtensionProperties` returns the OOM error, which is weird.

**Comment by Nijaitchy** [comment]
Tried some other example projects + deleted all downloaded crates,
still the same error.

**Comment by tomaka** [comment]
You should try running `vulkaninfo` from the official Vulkan SDK, or alternatively any Vulkan program that doesn't use vulkano, in order to check whether this is a driver problem or a problem with vulkano.

**Comment by Nijaitchy** [comment]
After trying it with the official SDK,
I found out that only a part of the R7 series is supported...
Sorry for taking your time.
