### ISSUE TITLE
impl_vertex! on struct with several members

### ISSUE THREAD

**Issue by SiebenCorgie** [tomaka/vulkano#625]
Hi, 
I am currently learning to use vulkano. I created a Vertex struct which looks like this:
```
#[derive(Clone,Copy)]
pub struct Vertex {
    pos: [f32; 3],
    tex_coord: [f32; 2],
    normal: [f32; 3],
    tangent: [f32; 3],
    color: [f32; 3],
}
```
However I can't do
```
impl_vertex!(Vertex, pos);
impl_vertex!(Vertex,tex_coord);
etc..
```
for it (`error[E0119]: conflicting implementations of trait 'vulkano::pipeline::vertex::Vertex' for type 'main::Vertex' `

Am I missing something or is it just not planed to have several members?

thanks!
-siebencorgie

**Comment by tomaka** [comment]
```rust
impl_vertex!(Vertex, pos, tex_coord, normal, tangent, color);
```

**Comment by SiebenCorgie** [comment]
Well, easier then I thought!
Thanks for the fast reply!
