### ISSUE TITLE
Remove PipelineLayoutDescNames

### ISSUE THREAD

**Issue by tomaka** [tomaka/vulkano#631]
Requires an API breaking change. Should be done before version 0.6 is released.

**Comment by tomaka** [comment]
Also can't be done before `simple_descriptor_set!` is removed.

**Comment by tyoc213** [comment]
is there something missing or is only management?

**Comment by tomaka** [comment]
The issue is about removing PipelineLayoutDescNames, not simple_descriptor_set.
