### ISSUE TITLE
No primary_one_time_submit found

### ISSUE THREAD

**Issue by mattbullen** [tomaka/vulkano#647]
While running the examples, I get this error for each of them:

"error: no associated item named `primary_one_time_submit` found for type `vulkano::command_buffer::AutoCommandBufferBuilder<_>` in the current scope"

Can't seem to find anything on Google or in the docs.

**Comment by tomaka** [comment]
This caused by the fact that this method has recently been added and is only available on the code on github.
But I published version 0.5.3. Just run `cargo update` and it should be available.

**Comment by mattbullen** [comment]
Works. What's the reason for the new method?

**Comment by tomaka** [comment]
There are multiple kinds of command buffers, plus some flags that you can pass on creation. `new` was not precise enough.
