### ISSUE TITLE
STRUCTURE_TYPE_DEBUG_REPORT misnamed.

### ISSUE THREAD

**Issue by krstoff** [tomaka/vulkano#674]
In vk-sys, VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT is named as STRUCTURE_TYPE_DEBUG_REPORT_CREATE_INFO_EXT, i.e. without the "CALLBACK" bit. This differs from the specification and can confuse people using the raw bindings.

**Comment by tomaka** [comment]
They probably changed it in the specs :-/
