### ISSUE TITLE
unstable library feature 'thread_id' needed for vulkano 0.5.6 and 0.5.4 on crates.io

### ISSUE THREAD

**Issue by SiebenCorgie** [tomaka/vulkano#698]
Hi,
I just saw that @tomaka updated Vulkano to 0.5.6 on crates.io.
I used a local git clone till now, but wanted to use the official releases.
However, if I add Vulkano to the cargo.toml and do `cargo build` (I do `cargo clean` and `cargo update` before) I get the following error from the compiler:
```
error: use of unstable library feature 'thread_id' (see issue #21507)
  --> /home/yyyy/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.5.6/src/command_buffer/pool/standard.rs:93:64
   |
93 |         let per_thread = match hashmap.entry(thread::current().id()) {
   |                                                                ^^
   |
   = help: add #![feature(thread_id)] to the crate attributes to enable
```
I tried to go back to Vulkano 0.5.5 from crates.io but there is the same problem.

Is this a problem on my side or a problem of Vulkano?
If it's on my side, how do I fix this?

Thanks for the help!

-siebencorgie

**Comment by tomaka** [comment]
Just update your version of Rust and it should be good.

**Comment by SiebenCorgie** [comment]
Yep that worked,
thanks for your fast help.

-siebencorgie
