### ISSUE TITLE
SyncCommandBufferBuilderError Occurs with Multiple Passes

### ISSUE THREAD

**Issue by AustinJ235** [tomaka/vulkano#702]
I received a SyncCommandBufferBuilderError in my small game I have been toying about with after updating vulkano, so I reproduced the error based teapot example code, https://github.com/AustinJ235/vulkano-issue. It works as expected on 5.4 but on the newer stuff it doesn't. I get the following error:

``SyncCommandBufferBuilderError(Conflict { command1_name: "vkCmdBeginRenderPass", command1_param: "attachment 0", command1_offset: 0, command2_name: "vkCmdBindDescriptorSets", command2_param: "Image bound to descriptor 0 of set 0", command2_offset: 9 })``

I narrowed it down to this commit, https://github.com/tomaka/vulkano/commit/3303cbe9346c92042dfe0ec2f206bb1912a336bb, causing the error to start happening. Not sure if I am doing things correctly, but it did work fine prior to that commit.

**Comment by tomaka** [comment]
I think vulkano is correct.

Section 7.3 of the Vulkan specs:

> Image subresources used as attachments must not be used via any non-attachment usage for the duration of a render pass instance.

In other words it is forbidden to use `p1_color_buf` before calling `end_render_pass()`.

**Comment by tomaka** [comment]
For your use case, Vulkan provides input attachments.

Add `p1_color` in the `input: []` array in your render pass macro:

```rust
    }, {
        color: [p2_color],
        depth_stencil: {},
        input: [p1_color]
    }
```

Then just replace this:

```glsl
layout(set = 0, binding = 0) uniform sampler2D color_tex;
```

With this:

```glsl
layout(input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput color_tex;
```

And this:

```glsl
out_color = texture(color_tex, in_coords);
```

With this:

```glsl
out_color = subpassLoad(u_color);
```

`subpassLoad` can only load the pixel at the current location in the fragment shader. It is a restriction of input attachments. If you don't like it, you will have to create multiple render passes.

**Comment by AustinJ235** [comment]
Well in my case i'd like it to be sampled. I did some research on the topic of reusing attachments and you do seem to be correct there. I redid the example with a true multi-pass way. Can you let me know if that is the proper way to do before you break my future illegal code...?

**Comment by tomaka** [comment]
> Can you let me know if that is the proper way to do before you break my future illegal code...?

Using multiple render passes is the correct way, yes.
