### ISSUE TITLE
Obtuse runtime panic when struct field name doesn't match shader attribute name

### ISSUE THREAD

**Issue by bch29** [tomaka/vulkano#87]
When a vertex struct field name doesn't match its respective shader attribute name, you get a runtime panic which is hard to decipher.

-------

## Original, uninformed issue:

If a struct's field is named `col` and it is used as a vertex, the program will crash at runtime with an error like this:

```
thread '<main>' panicked at 'missing vertex attrib', src/libcore/optio
n.rs:704                                                             
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/triangle` (exit code: 101)
```

To reproduce, just `s/position/col` in the triangle example.

This caused me a great deal of frustration when I was trying to modify the triangle example to accept a buffer of vertex colours. Changing the name of the field wasn't something I thought to try for a long time.

**Comment by tomaka** [comment]
This panic happens because the attribute in your vertex shader must have the same name as the fields of the struct.

I agree that the error is not great though, and must be improved.

**Comment by bch29** [comment]
OK, that makes sense. I've renamed the issue.
